---
collections:
  - ansible.posix
  - containers.podman
  - community.general
  - ovirt.ovirt
  - community.vmware
  - community.libvirt
  - ansible.windows
  - name: https://github.com/kenmoini/ansible-collection-hyperv.git
    type: git
    version: main
