version: 3

#build_arg_defaults:
#  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest'
#  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:latest'
#  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-cv'


additional_build_files:
    - src: ansible.cfg
      dest: configs

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_builder: |
    RUN whoami
    RUN cat /etc/os-release
    RUN dnf update -y && dnf upgrade -y
    RUN dnf install http://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm -y
    RUN  dnf install python3-ovirt-engine-sdk4 libxml2-devel openssl-devel libcurl-devel python3-devel gcc -y
    #RUN pip install --upgrade pip && pip install setuptools-rust && pip install cryptography
  append_builder:
    - RUN echo This is a post-install command!
