version: 3

#build_arg_defaults:
#  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest'
#  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:latest'
#  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-cv'


additional_build_files:
    - src: ansible.cfg
      dest: configs

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  python_interpreter:
      package_system: "python3"
      python_path: "/usr/bin/python3.11"

additional_build_steps:
  prepend_builder: |
    RUN whoami
    RUN cat /etc/os-release
    RUN dnf update -y && dnf upgrade -ypip
    RUN dnf install http://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm -y
    RUN  dnf install python3-ovirt-engine-sdk4 libxml2-devel openssl-devel libcurl-devel python3-devel gcc python3-pip  python3.11-devel -y
    RUN pip3 install --upgrade pip3 && pip install setuptools-rust wheel && pip3 install cryptography pycurl ovirt_imageio
  append_builder:
    - RUN echo This is a post-install command!
