version: 3

#build_arg_defaults:
#  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest'
#  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:latest'
#  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-cv'


additional_build_files:
    - src: ansible.cfg
      dest: configs

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  python_interpreter:
      package_system: "python3"
      python_path: "/usr/bin/python3.8"

additional_build_steps:
  prepend_base: |
    RUN whoami
    RUN python3 --version
    RUN cat /etc/os-release
    RUN dnf update -y && dnf upgrade -y
    RUN dnf install http://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm -y
    RUN  dnf install python3-ovirt-engine-sdk4 libxml2-devel openssl-devel libcurl-devel gcc python3-pip  python38-devel python3-pycurl -y
    RUN python3.8 -m pip install --upgrade pip && python3.8 -m pip install setuptools-rust wheel && \
      python3.8 -m pip install  cryptography && python3.8 -m pip install  pycurl  && python3.8 -m pip install  ovirt_imageio 
  prepend_builder: |
    RUN whoami
    RUN python3 --version
    RUN cat /etc/os-release
    RUN dnf update -y && dnf upgrade -y
    RUN dnf install http://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm -y
    RUN  dnf install python3-ovirt-engine-sdk4 libxml2-devel openssl-devel libcurl-devel gcc python3-pip  python38-devel python3-pycurl -y
    RUN python3.8 -m pip install --upgrade pip && python3.8 -m pip install setuptools-rust wheel && \
      python3.8 -m pip install  cryptography && python3.8 -m pip install  pycurl  && python3.8 -m pip install  ovirt_imageio 
  prepend_final: |
    RUN whoami
    RUN python3 --version
    RUN cat /etc/os-release
    RUN dnf update -y && dnf upgrade -y
    RUN dnf install http://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm -y
    RUN  dnf install python3-ovirt-engine-sdk4 libxml2-devel openssl-devel libcurl-devel gcc python3-pip  python38-devel python3-pycurl -y
    RUN python3.8 -m pip install --upgrade pip && python3.8 -m pip install setuptools-rust wheel && \
      python3.8 -m pip install  cryptography && python3.8 -m pip install  pycurl  && python3.8 -m pip install  ovirt_imageio 
  append_builder:
    - RUN echo This is a post-install command!
